-- Lobby
CREATE TABLE LOBBY
(
	LOBBY_ID INT(10) AUTO_INCREMENT NOT NULL,
	MAX_USER_COUNT INT(10) NOT NULL DEFAULT 0,
	CURRENT_COUNT INT(10) NOT NULL DEFAULT 0,
	LOBBY_NAME VARCHAR(30) NOT NULL,
	PRIMARY KEY (LOBBY_ID)
);

INSERT INTO LOBBY
(GAME_ID, HOST_ID, MAX_USER_COUNT, CURRENT_COUNT, LOBBY_NAME)
VALUES
(0, 0, 4, 0, "REDWOODY'S LOBBY");
