-- red_db --
CREATE TABLE RED_USER
(
	USER_ID INT AUTO_INCREMENT NOT NULL,
	ACCOUNT_MAIL VARCHAR(30) NOT NULL,
    ACCOUNT_PWD CHAR(30) NOT NULL,
	USER_NAME VARCHAR(16) NOT NULL,
	LAST_LOGIN_DATE TIMESTAMP,
	SIGNUP_DATE DATE NOT NULL,
	OPEN_AUTH_TYPE VARCHAR(30),
	IS_LOGGED_IN BOOLEAN,
	CONSTRAINT USER_PK PRIMARY KEY(USER_ID),
    CONSTRAINT USER_AK1 UNIQUE (USER_NAME)
);

INSERT INTO RED_USER (ACCOUNT_MAIL, ACCOUNT_PWD, USER_NAME, SIGNUP_DATE, IS_LOGGED_IN)
VALUES ('A@mail.com', '123', 'A', now(), 0);

INSERT INTO RED_USER (ACCOUNT_MAIL, ACCOUNT_PWD, USER_NAME, SIGNUP_DATE, IS_LOGGED_IN)
VALUES ('B@mail.com', '123', 'B', now(), 0);

INSERT INTO RED_USER (ACCOUNT_MAIL, ACCOUNT_PWD, USER_NAME, SIGNUP_DATE, IS_LOGGED_IN)
VALUES ('C@mail.com', '123', 'C', now(), 0);

INSERT INTO RED_USER (ACCOUNT_MAIL, ACCOUNT_PWD, USER_NAME, SIGNUP_DATE, IS_LOGGED_IN)
VALUES ('D@mail.com', '123', 'D', now(), 0);

SELECT ACCOUNT_MAIL, ACCOUNT_PWD, USER_NAME, USER_ID, LAST_LOGIN_DATE, IS_LOGGED_IN
FROM RED_USER
WHERE USER_NAME = 'test02';

SELECT * FROM RED_USER;

DROP TABLE RED_USER;
DELETE FROM RED_USER;

