-- red_db --
CREATE TABLE RED_USER
(
	USER_ID INT(10) AUTO_INCREMENT NOT NULL,
	ACCOUNT_ID CHAR(30) NOT NULL,
	ACCOUNT_PWD CHAR(30) NOT NULL,
	ACCOUNT_MAIL VARCHAR(30) NOT NULL,
	USER_NAME VARCHAR(16) NOT NULL,
	LAST_LOGIN_DATE TIMESTAMP,
	SIGNUP_DATE DATE NOT NULL,
	OPEN_AUTH_TYPE INT(10),
	IS_LOGGED_IN BOOLEAN,
	PRIMARY KEY(USER_ID)
);

INSERT INTO RED_USER
(ACCOUNT_ID, ACCOUNT_PWD, ACCOUNT_MAIL, USER_NAME, SIGNUP_DATE, IS_LOGGED_IN)
VALUES
('test02', '1234', 'test@mail.com', 'test02', DATE_FORMAT(now(), '%Y-%m-%d'), 0);

INSERT INTO RED_USER
(ACCOUNT_ID, ACCOUNT_PWD, ACCOUNT_MAIL, USER_NAME, SIGNUP_DATE, IS_LOGGED_IN)
VALUES
('test01', '1234', 'test01@mail.com', 'test01', NOW(), 0);

SELECT ACCOUNT_ID, ACCOUNT_PWD, USER_NAME, USER_ID, LAST_LOGIN_DATE, IS_LOGGED_IN
FROM RED_USER
WHERE ACCOUNT_ID = 'test02';

SELECT *
FROM RED_USER;
